services:

  nginx:
    container_name: NGINX
    image: nginx
    build: ./requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      inception-network:
        ipv4_address: 10.0.0.1
    volumes:
      - ${CERTS_SSL}:/etc/nginx/certs
      - wp-data:/var/www/html
    depends_on:
      - wordpress
      - adminer
    restart: unless-stopped

  mariadb:
    container_name: MariaDB
    image: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    networks:
      inception-network:
        ipv4_address : 10.0.0.2
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: WordPress
    image: wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    networks:
      inception-network:
        ipv4_address : 10.0.0.3
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

  redis:
    container_name: RedisCache
    image: redis
    build: ./requirements/redis/
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      inception-network:
        ipv4_address : 10.0.0.4
    depends_on:
      - wordpress
    restart: unless-stopped

  ftp:
    container_name: FTP
    image: ftp
    build: ./requirements/ftp/
    env_file:
      - .env
    ports:
      - "21:21"
    networks:
      inception-network:
        ipv4_address : 10.0.0.5
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped

  adminer:
    container_name: AdminerDB
    image: adminer
    build: ./requirements/adminer/
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      inception-network:
        ipv4_address : 10.0.0.6
    depends_on:
      - mariadb
    restart: unless-stopped


networks:
  inception-network:
    name: inception-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.254


volumes:
  wp-data:
    name: "wp"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/wp
    # external:

  db-data:
    name: "db"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/db
    # external:
