version: '3.8'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/ # or:
      # context: ./requirements/nginx/
      # dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wp-data:/var/
    networks:
      inception-network:
        aliases:
          - nginx-network
    # depends_on:
    #   - 
    restart: always
    ports:
      - "443:443"
      - "8080:8080"

  # mariadb:
  #   build: ./requirements/mariadb/
  #   env_file:
  #     - .env
  #   volumes:
  #     -
  #   networks:
  #     inception-network:
  #       aliases:
  #         - db
  #   # restart: unless-stopped
  #   # depends_on:
  #   #   - 

  # wordpress:
  #   build: ./requirements/wordpress/
  #   env_file:
  #     - .env
  #   volumes:
  #     -
  #   networks:
  #     inception-network:
  #       aliases:
  #         - wp
  #   # restart: unless-stopped
  #   # depends_on:
  #   #   - 


networks:
  inception-network:


volumes:
  db-data:
    name: "db-data"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/db
    # external:

  wp-data:
    name: "wp-data"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/wp
    # external:
