version: '3.8'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    env_file:
      - .env
    volumes:
      - ${CERTS_SSL}:/etc/nginx/certs
      - wp-data:/var/www/html
    networks:
      inception-network:
        aliases:
          - nginx-network
    # depends_on:
    #   - 
    restart: unless-stopped
    ports:
      - "443:443"
      - "8080:8080"

  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress/
  #   env_file:
  #     - .env
  #   # volumes:
  #   #   -
  #   networks:
  #     inception-network:
  #       aliases:
  #         - wp-network
  #   # depends_on:
  #   #   - 
  #   restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb/
    env_file:
      - .env
    # volumes:
    #   -
    networks:
      inception-network:
        aliases:
          - db-network
    restart: unless-stopped
    # depends_on:
    #   - 


networks:
  inception-network:


volumes:
  wp-data:
    name: "wp-data"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/wp
    # external:

  db-data:
    name: "db-data"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/db
    # external:
