version: '3.8'

services:

  nginx:
    build: ./requirements/nginx/ # or:
      # context: ./requirements/nginx/
      # dockerfile: Dockerfile
    # container_name: nginx # not necessary (?)
    env_file:
      - .env
    volumes:
      -
    networks:
      inception-network:
        aliases:
          - nginx
    # depends_on:
    #   - 
    # restart: unless-stopped
    ports:
      - "443"

  mariadb:
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      -
    networks:
      inception-network:
        aliases:
          - db
    # restart: unless-stopped
    # depends_on:
    #   - 

  wordpress:
    build: ./requirements/wordpress/
    env_file:
      - .env
    volumes:
      -
    networks:
      inception-network:
        aliases:
          - wp
    # restart: unless-stopped
    # depends_on:
    #   - 


networks:
  inception-network:


volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device:
    # name:
    # external:

  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device:
    # name:
    # external:
