version: '3.8'

services:

  nginx:
    build: ./requirements/nginx/
      # context: ./requirements/nginx/
      # dockerfile: Dockerfile
    # container_name: nginx
    env_file:
      - .env
    volumes:
      -
    ports:
      - "8080"

  # mariadb:
  #   build:
  #     context: ./requirements/mariadb/
  #     dockerfile: Dockerfile

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress/
  #     dockerfile: Dockerfile


volumes:
  db_volume:

  wp_volume:
