services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    env_file:
      - .env
    networks:
      # - inception-network
      inception-network:
        ipv4_address: 10.0.0.1
        # aliases:
        #   - nginx-network
    volumes:
      - ${CERTS_SSL}:/etc/nginx/certs
      - wp-data:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443"
      - "8080:8080"

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    networks:
      # - inception-network
      inception-network:
        ipv4_address : 10.0.0.2
        # aliases:
          # - db-network
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    networks:
      # - inception-network
      inception-network:
        ipv4_address : 10.0.0.3
        # aliases:
        #   - wp-network
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped


networks:
  inception-network:
    name: inception-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.254


volumes:
  wp-data:
    name: "wp"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/wp
    # external:

  db-data:
    name: "db"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES}/db
    # external:
